### ISSUE TITLE
Bot is not downloading torrents

### ISSUE THREAD

**Issue by denistravis** [alfiananda84/TorrentLeech-Gdrive#2]
The bot is usually stuck at fetching metadata with no response for a long period./ytdl works fine
![Screenshot_20200706-101659](https://user-images.githubusercontent.com/54004935/86566597-9bd7a780-bf72-11ea-90d4-7c6e9223e05f.png)

**Comment by alfiananda84** [comment]
Seeder link dead,try another torrent

**Comment by denistravis** [comment]
I tried with another torrent with about 1700 seeders but still no response
![Screenshot_20200706-124950_1594029064151](https://user-images.githubusercontent.com/54004935/86580638-a94b5c80-bf87-11ea-92d3-a9db65231df7.jpg)

**Comment by alfiananda84** [comment]
Send the torrent

**Comment by denistravis** [comment]
magnet:?xt=urn:btih:42F3CE2320F87AE33B6762A6648EE8F192CF4461&dn=Force.of.Nature.2020.720p.BluRay.800MB.x264-GalaxyRG+%E2%AD%90&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.iamhansen.xyz%3A2000%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce&tr=udp%3A%2F%2Fexplodie.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.moeking.me%3A6969%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce

**Comment by alfiananda84** [comment]
Working here

**Comment by alfiananda84** [comment]
![Screenshot_20200706-165711~2](https://user-images.githubusercontent.com/63289446/86581547-6babfb00-bfaa-11ea-84a2-6c972a61f140.png)

**Comment by denistravis** [comment]
Redeployed but still having same problems. Here are my config vars. What's missing?
![Screenshot_20200706-131624_1594031044991](https://user-images.githubusercontent.com/54004935/86583492-0cd78900-bf8c-11ea-8687-34b6a73fc139.jpg)

**Comment by alfiananda84** [comment]
Delete  customfilename & maxtimewaittorrent and try again

**Comment by denistravis** [comment]
Thanks. Working now.
