### ISSUE TITLE
#Request download complete message

### ISSUE THREAD

**Issue by denistravis** [alfiananda84/TorrentLeech-Gdrive#4]
Hi can we get a message informing user that their download is complete, such as these instead of editing the original message. Thanks
![Screenshot_20200711-065813_1594440006892](https://user-images.githubusercontent.com/54004935/87216056-b29c4680-c344-11ea-97a1-372d47e4e204.jpg)
![Screenshot_20200711-065752_1594439967485](https://user-images.githubusercontent.com/54004935/87216077-d1024200-c344-11ea-9b07-89aae43e4e6e.jpg)

**Comment by alfiananda84** [comment]
Use original one,because i removed it
